name: My first workflow
on: push

jobs:
 my-first-job:
   runs-on: ubuntu-latest
   steps:
     - name: Echo Hello World
       run: echo "Hello World" 

 my-second-job:
   runs-on: ubuntu-latest
   steps:
     - name: Echo Hello World
       run: echo "Bye World" 

 


